### ISSUE TITLE
Use upstream pulp/crane repo

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/raas#37]
Currently we're using a [fork](https://github.com/aweiteka/crane) of pulp/crane [patched](https://github.com/aweiteka/crane/commit/a7906de64fb64f367d3a7386abc8e7832ea84dcf) for deploying on OpenShift. This is not desirable. Two issues:
1. no rhsm package in python-2.7 cartridge. We might be able to install this from the upstream repo. This works locally so we might be able to add this to requirements.txt: `pip install git+https://github.com/candlepin/python-rhsm.git`
2. `from .app import create_app` must be changed to `from crane.app import create_app`. Not sure what the path to resolution is.

**Comment by aweiteka** [comment]
adding `git+https://github.com/candlepin/python-rhsm.git` to `requirements.txt` didn't work.

```
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1] mod_wsgi (pid=62315): Target WSGI script '/var/lib/openshift/54f4d24f4382ec81af00000d/app-root/runtime/repo/crane/wsgi.py' cannot be loaded as Python module.
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1] mod_wsgi (pid=62315): Exception occurred processing WSGI script '/var/lib/openshift/54f4d24f4382ec81af00000d/app-root/runtime/repo/crane/wsgi.py'.
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1] Traceback (most recent call last):
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]   File "/var/lib/openshift/54f4d24f4382ec81af00000d/app-root/runtime/repo/crane/wsgi.py", line 1, in <module>
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]     from crane.app import create_app
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]   File "/var/lib/openshift/54f4d24f4382ec81af00000d/app-root/runtime/repo/crane/app.py", line 6, in <module>
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]     from crane.views import crane, v1
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]   File "/var/lib/openshift/54f4d24f4382ec81af00000d/app-root/runtime/repo/crane/views/crane.py", line 6, in <module>
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]     from .. import app_util
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]   File "/var/lib/openshift/54f4d24f4382ec81af00000d/app-root/runtime/repo/crane/app_util.py", line 6, in <module>
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]     from rhsm import certificate
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]   File "/var/lib/openshift/54f4d24f4382ec81af00000d/python/virtenv/lib/python2.7/site-packages/rhsm/certificate.py", line 33, in <module>
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1]     from M2Crypto import X509, RSA
[Mon Mar 02 16:14:59 2015] [error] [client 127.11.132.1] ImportError: No module named M2Crypto
66.187.233.206 - - [02/Mar/2015:16:14:58 -0500] "GET /v1/_ping HTTP/1.1" 500 632 "-" "python-requests/2.5.0 CPython/2.7.8 Linux/3.18.7-200.fc21.x86_64"
```

**Comment by aweiteka** [comment]
Need upstream pulp/crane help on this.

**Comment by aweiteka** [comment]
rhsm is installing fine from source and we're able to specify a tagged release. M2Crypto is a dependency of rhsm which is failing during pip install. `requirements.txt`:

```
Flask>=0.9
# for pkg_resources
setuptools
M2Crypto
git+https://github.com/candlepin/python-rhsm.git@python-rhsm-1.13.10-1
```

**Comment by aweiteka** [comment]
The crane relative import failure resolution is to use an alternative wsgi file crane has. The verified fix is to change the [WSGI env var](https://github.com/aweiteka/raas/blob/master/raas.py#L889):

```
OPENSHIFT_PYTHON_WSGI_APPLICATION='deployment/crane.wsgi'
```

**Comment by aweiteka** [comment]
It appears M2Crypto dependencies must be installed via RPM using a custom cartridge.
